### ISSUE TITLE
Your sile looks like vomit when viewed on a phone

### ISSUE THREAD

**Issue by kodfodrasz** [eevee/eev.ee#3]
I have seen articles from your site linked as top articles on hacker news the second time within a week. The article called "the sad state of web app deployment" had a title suggesting an interesting article. Unfortunately the contents and navigation elements are scattered round the screen like the half-digested pieces of food in the toilet after vomit. 

Sadly I could not read it because of the sad state of static site development skills of the spindoctor bashing webapp development.

IMHO this would undermine the authenticity of the article,  even if it could be read at all.

**Comment by eevee** [comment]
Works on my machine.

**Comment by erisdev** [comment]
works for me. tested with mobile firefox 40.0.3 and android browser 4.4.4-?????. sounds like your device is misconfigured. attitude may need recalibration as well.

**Comment by LB--** [comment]
![image](https://cloud.githubusercontent.com/assets/1296838/9971620/e519bfd4-5e22-11e5-9e78-872aacf30073.png) ![image](https://cloud.githubusercontent.com/assets/1296838/9971633/fac72fba-5e22-11e5-8fb2-be2234739031.png)

I didn't take those screenshots, they are taken from https://what.thedailywtf.com/t/the-sad-state-of-atwoods-web-app-deployment/51305/1

**Comment by kodfodrasz** [comment]
I'm most sorry. You were selected as a member of a group in A-B testing in a social experiment, where the response time to bug reports when kind and when harsh wording is used is measured. The coin flipped this way for this issue. :(

**Comment by ahoka** [comment]
The site looks retarded. It was an insta-close upon first sight (and nothing of value was lost).

**Comment by charmander** [comment]
![](https://cloud.githubusercontent.com/assets/1889843/10001022/8e3fe81c-6054-11e5-86e5-94062a68413d.png)
> and nothing of value was lost
