### ISSUE TITLE
Your blog is so great that I also wish it were secure

### ISSUE THREAD

**Issue by konklone** [eevee/eev.ee#9]
Your [latest post](http://eev.ee/blog/2016/02/15/everyones-offended-these-days/) has made me a convert and I've added your feed to my feed reader.

It'd be nice to be able to visit your site securely, though -- I don't like being vulnerable to [ISP tracking](http://www.forbes.com/sites/kashmirhill/2014/10/28/find-out-whether-this-privacy-killing-super-cookie-is-on-your-phone/) or [random companies piggybacking on the ISP](http://webpolicy.org/2015/01/14/turn-verizon-zombie-cookie/) or [more novel and dangerous attacks](https://citizenlab.org/2015/04/chinas-great-cannon/).

Can floraverse.com get you a free cert from [Let's Encrypt](https://letsencrypt.org/) or a cheap one from [SSLMate](https://sslmate.com) or something?

**Comment by eevee** [comment]
I hadn't bothered since it's all static text, but fair enough.  I'll snag one soon.  I've been meaning to give Let's Encrypt a try; maybe it'll be less of a pain in the ass than StartSSL.  :)

**Comment by eevee** [comment]
That was absolutely less of a pain in the ass!  Thanks for the nudge, this was super easy.

**Comment by konklone** [comment]
That's awesome! =) Yay for easy security!
